#!/usr/bin/env bash
# Installs terminal-node-agent on a WORKER node (e.g. the Lenovo M910) --
# run this ON THE WORKER NODE ITSELF, not on the controller (Dell). It
# never touches the controller's own systemd units, config, or tmux
# sessions -- see this script's own printed final step for the one manual
# action still required on the controller (registering this node in its
# config.yaml).
#
# Usage:
#   ./install-node-agent.sh --controller <http://controller-host:8766> --node-id <id> [options]
#
# Required:
#   --controller URL     Controller's terminal-mcp-http base URL (e.g. http://192.168.1.10:8766)
#   --node-id ID          This node's own id (e.g. "m910") -- must match what you'll register
#                          on the controller's config.yaml nodes.remote[].node_id
#
# Optional:
#   --repo-dir DIR         Where to clone/use the terminal-mcp repo (default: ~/terminal-mcp)
#   --repo-url URL         Git remote to clone from (default: unset -- if --repo-dir doesn't
#                           already contain a checkout, you'll be told to clone it yourself)
#   --port PORT             Node agent's own listen port (default: 8790)
#   --host HOST             Node agent's own bind address (default: 127.0.0.1 -- see the
#                           systemd unit's own comment before changing this)
#   --heartbeat-interval N  Seconds between heartbeat pushes to the controller (default: 20)
#   --no-systemd            Print the commands instead of running systemctl (for a non-systemd host)
set -euo pipefail

CONTROLLER_URL=""
NODE_ID=""
REPO_DIR="$HOME/terminal-mcp"
REPO_URL=""
AGENT_PORT=8790
AGENT_HOST=127.0.0.1
HEARTBEAT_INTERVAL=20
USE_SYSTEMD=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --controller) CONTROLLER_URL="$2"; shift 2 ;;
    --node-id) NODE_ID="$2"; shift 2 ;;
    --repo-dir) REPO_DIR="$2"; shift 2 ;;
    --repo-url) REPO_URL="$2"; shift 2 ;;
    --port) AGENT_PORT="$2"; shift 2 ;;
    --host) AGENT_HOST="$2"; shift 2 ;;
    --heartbeat-interval) HEARTBEAT_INTERVAL="$2"; shift 2 ;;
    --no-systemd) USE_SYSTEMD=0; shift ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$CONTROLLER_URL" || -z "$NODE_ID" ]]; then
  echo "Error: --controller and --node-id are both required. See --help." >&2
  exit 1
fi
if [[ ! "$NODE_ID" =~ ^[a-zA-Z0-9_-]+$ ]]; then
  echo "Error: --node-id must be alphanumeric/-/_ only (got: $NODE_ID)" >&2
  exit 1
fi

echo "== Terminal MCP node agent installer =="
echo "  node-id:    $NODE_ID"
echo "  controller: $CONTROLLER_URL"
echo "  repo-dir:   $REPO_DIR"
echo

# -- 1. Repo checkout --------------------------------------------------------
if [[ -d "$REPO_DIR/.git" ]]; then
  echo "-> Found existing repo checkout at $REPO_DIR, leaving it as-is (pull/checkout yourself if you need a specific version)."
elif [[ -n "$REPO_URL" ]]; then
  echo "-> Cloning $REPO_URL into $REPO_DIR"
  git clone "$REPO_URL" "$REPO_DIR"
else
  echo "Error: $REPO_DIR does not exist and --repo-url was not given -- either clone the repo" >&2
  echo "there yourself first, or re-run with --repo-url <git-url>." >&2
  exit 1
fi

# -- 2. Python venv + install -------------------------------------------------
cd "$REPO_DIR"
if [[ ! -d .venv ]]; then
  echo "-> Creating .venv"
  python3 -m venv .venv
fi
echo "-> Installing terminal-mcp (pip install -e .)"
./.venv/bin/pip install --quiet --upgrade pip
./.venv/bin/pip install --quiet -e .

# -- 3. This node's own token -------------------------------------------------
ENV_FILE="$REPO_DIR/node-agent.env"
if [[ -f "$ENV_FILE" ]]; then
  echo "-> $ENV_FILE already exists, leaving its token as-is."
else
  TOKEN=$(python3 -c "import secrets; print(secrets.token_hex(32))")
  umask 077
  cat > "$ENV_FILE" <<EOF
# Shared secret for THIS node agent -- generated by install-node-agent.sh.
# Register the SAME value on the controller as an environment variable
# named TERMINAL_MCP_NODE_TOKEN_$(echo "$NODE_ID" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
# (see this script's own final instructions). Never commit this file,
# never log this value, never send it anywhere except that one variable.
TERMINAL_MCP_NODE_TOKEN=$TOKEN
EOF
  chmod 600 "$ENV_FILE"
  echo "-> Generated a new token at $ENV_FILE (mode 600)"
fi
TOKEN_VALUE=$(grep '^TERMINAL_MCP_NODE_TOKEN=' "$ENV_FILE" | cut -d= -f2-)

# -- 4. config.yaml -----------------------------------------------------------
if [[ ! -f "$REPO_DIR/config.yaml" ]]; then
  echo "-> No config.yaml found -- copying config.example.yaml as a starting point."
  echo "   Review it (allowed_session_patterns, session_lifecycle.allowed_cwd_roots) before starting the service."
  cp "$REPO_DIR/config.example.yaml" "$REPO_DIR/config.yaml"
fi

# -- 5. systemd unit -----------------------------------------------------------
UNIT_DIR="$HOME/.config/systemd/user"
UNIT_PATH="$UNIT_DIR/terminal-node-agent.service"
UNIT_CONTENT=$(cat <<EOF
[Unit]
Description=Terminal MCP node agent ($NODE_ID)
After=default.target

[Service]
Type=simple
WorkingDirectory=$REPO_DIR
EnvironmentFile=$ENV_FILE
Environment=TERMINAL_MCP_CONFIG=$REPO_DIR/config.yaml
ExecStart=$REPO_DIR/.venv/bin/terminal-node-agent --node-id $NODE_ID --controller-url $CONTROLLER_URL --host $AGENT_HOST --port $AGENT_PORT --heartbeat-interval-seconds $HEARTBEAT_INTERVAL
Restart=always
RestartSec=3
RestartSteps=6
RestartMaxDelaySec=60
StartLimitIntervalSec=300
StartLimitBurst=8
MemoryMax=512M
TasksMax=256
ProtectSystem=full
ProtectHome=read-only
ReadWritePaths=%h/.local/state/terminal-mcp
NoNewPrivileges=yes
SystemCallFilter=@system-service

[Install]
WantedBy=default.target
EOF
)

if [[ "$USE_SYSTEMD" -eq 1 ]]; then
  mkdir -p "$UNIT_DIR"
  echo "$UNIT_CONTENT" > "$UNIT_PATH"
  echo "-> Wrote $UNIT_PATH"
  systemctl --user daemon-reload
  systemctl --user enable --now terminal-node-agent.service
  echo "-> Started terminal-node-agent.service (systemctl --user status terminal-node-agent to check)"
  loginctl enable-linger "$USER" 2>/dev/null || echo "   (could not enable-linger automatically -- run 'loginctl enable-linger $USER' as root/sudo so this survives logout)"
else
  echo "-> --no-systemd given: unit content that WOULD have been written to $UNIT_PATH:"
  echo "$UNIT_CONTENT"
  echo "-> Start it manually with:"
  echo "   $REPO_DIR/.venv/bin/terminal-node-agent --node-id $NODE_ID --controller-url $CONTROLLER_URL --host $AGENT_HOST --port $AGENT_PORT"
fi

echo
echo "== Node agent installed. ONE MORE STEP -- on the CONTROLLER (Dell) =="
echo
echo "1) Add this node to the controller's config.yaml (nodes.remote list):"
echo
echo "     nodes:"
echo "       remote:"
echo "         - node_id: $NODE_ID"
echo "           display_name: \"$NODE_ID\""
echo "           hostname: \"$(hostname)\""
echo "           endpoint: \"http://$(hostname -I 2>/dev/null | awk '{print $1}'):$AGENT_PORT\"  # verify this LAN address is reachable from the controller"
echo "           token_env: TERMINAL_MCP_NODE_TOKEN_$(echo "$NODE_ID" | tr '[:lower:]' '[:upper:]' | tr '-' '_')"
echo
echo "2) Export the SAME token this node generated as that environment variable"
echo "   wherever the controller's terminal-mcp-http.service reads its own"
echo "   environment from (its systemd unit's EnvironmentFile, or an /etc/"
echo "   systemd/system/terminal-mcp-http.service.d/ override -- never inline"
echo "   in the unit file itself):"
echo
echo "     TERMINAL_MCP_NODE_TOKEN_$(echo "$NODE_ID" | tr '[:lower:]' '[:upper:]' | tr '-' '_')=$TOKEN_VALUE"
echo
echo "3) Restart the controller's terminal-mcp-http.service (safe restart --"
echo "   verify existing tmux sessions/session_created timestamps are"
echo "   unchanged before/after, same as any other restart of this service)."
echo
echo "4) Verify with: terminal-mcp-doctor nodes   (on the controller)"
echo "   -- $NODE_ID should show status=online within one heartbeat interval (~${HEARTBEAT_INTERVAL}s)."
